import test from 'node:test';
import assert from 'node:assert/strict';
import {categories,validateReview,reconcile,blockers} from '../src/discrepancies.mjs';
import {measure,validateMeasurements,mergeMeasurements} from '../src/evidence.mjs';
import {defaults,validateConfig} from '../src/config.mjs';
const review=()=>({coverage:categories.map(category=>({category,status:'reviewed',evidence:'Observed'})),issues:[],resolutions:[]});
const issue={key:'hero',component:'hero',category:'geometry',severity:'major',kind:'layout',description:'Mismatch',expected:'Portrait',actual:'Square',evidence:'Bounds',remedy:'Resize'};
for(const category of categories)test(`coverage must include ${category}`,()=>{const r=review();r.coverage=r.coverage.filter(c=>c.category!==category);assert.throws(()=>validateReview(r));});
for(const [field,value] of Object.entries({severity:'none',kind:'ignored',category:'unknown',evidence:'',expected:'',actual:'',remedy:''}))test(`invalid issue ${field} is rejected`,()=>{const r=review();r.issues=[{...issue,[field]:value}];assert.throws(()=>validateReview(r));});
test('empty judge samples cannot resolve an issue',()=>{assert.throws(()=>reconcile([{...issue,status:'open',history:[]}],[],'b'));});
test('reconciliation preserves input, history and unresolved minor issues',()=>{const r=review();r.issues=[{...issue,severity:'minor'}];const old=reconcile([],[r],'a'),snapshot=structuredClone(old);const next=reconcile(old,[r],'b');assert.deepEqual(old,snapshot);assert.equal(next[0].history.length,2);assert.equal(next[0].status,'open');assert.equal(blockers(next).length,0);});
test('unverified category creates a blocking constraint',()=>{const r=review();r.coverage[0].status='unverified';assert.equal(blockers(reconcile([],[r],'a'))[0].kind,'constraint');});
const check={key:'hero',selector:'id:hero',metric:'width',expected:0.4,tolerance:0.01,severity:'major'};
const scenario={width:200,height:400};
const capture={pixelRatio:2,elements:[{id:'hero',fontSize:24,bounds:{x:20,y:80,width:80,height:100}},{id:'heading',bounds:{x:20,y:20,width:80,height:40}}]};
for(const [metric,expected] of Object.entries({x:.1,y:.2,width:.4,height:.25,aspectRatio:.8,gap:.05,fontSize:24,touchSize:40}))test(`measure ${metric} uses documented units`,()=>{const r=measure([{...check,metric,expected,relativeTo:'id:heading'}],capture,scenario)[0];assert.equal(r.status,'resolved');assert.equal(r.actual,expected);});
test('ambiguous selectors and missing density cannot pass',()=>{assert.equal(measure([check],{elements:[...capture.elements,capture.elements[0]]},scenario)[0].status,'unverified');assert.equal(measure([{...check,metric:'touchSize'}],{elements:capture.elements},scenario)[0].status,'unverified');});
test('invalid native bounds cannot produce a successful measurement',()=>{assert.equal(measure([{...check,expected:0}],{elements:[{id:'hero',bounds:{x:0,y:0,width:0,height:100}}]},scenario)[0].status,'unverified');});
for(const c of [{...check,tolerance:-1},{...check,expected:Infinity},{...check,metric:'guess'},{...check,selector:'unknown:hero'}])test(`invalid measurement ${JSON.stringify(c)}`,()=>assert.throws(()=>validateMeasurements([c])));
test('duplicate measurement keys rejected',()=>assert.throws(()=>validateMeasurements([check,check])));
test('measurement merge retains model findings and replaces deterministic findings',()=>{const m=mergeMeasurements([{...issue,key:'model'},{...issue,key:'measurement:old'}],[{key:'measurement:new',status:'open'}],'r');assert.deepEqual(m.map(i=>i.key),['model','measurement:new']);assert.equal(m[1].verifiedRevision,'r');});
for(const [key,value] of Object.entries({maxCalls:0,maxIterations:1.5,maxMinutes:-1,maxUSD:NaN,callTimeoutSeconds:0}))test(`reject invalid budget ${key}`,()=>{const c=structuredClone(defaults);c.budgets[key]=value;assert.throws(()=>validateConfig(c));});
for(const platform of ['react-native','web','flutter','native'])test(`config accepts ${platform}`,()=>assert.equal(validateConfig({...structuredClone(defaults),platform}).platform,platform));
test('one reviewer cannot downgrade another reviewer’s critical finding',()=>{const a=review(),b=review();a.issues=[{...issue,severity:'critical'}];b.issues=[{...issue,severity:'minor'}];assert.equal(reconcile([],[a,b],'r')[0].severity,'critical');assert.equal(reconcile([],[b,a],'r')[0].severity,'critical');});
