import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {sourceRevision,approvalStatus} from '../src/provenance.mjs';
import {git,hash,writeJSON} from '../src/util.mjs';
async function repo(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'uih-provenance-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await git(root,'init');await fs.writeFile(path.join(root,'.gitignore'),'.uih/\nbuild/\n');await fs.writeFile(path.join(root,'app.js'),'one');await git(root,'add','.');return root;}
test('revision covers binary assets, deletion and untracked source but excludes ignored runtime and secrets',async t=>{const root=await repo(t),base=await sourceRevision(root);await fs.writeFile(path.join(root,'asset.png'),Buffer.from([0,1,255]));assert.notEqual(await sourceRevision(root),base);await fs.unlink(path.join(root,'asset.png'));assert.equal(await sourceRevision(root),base);await fs.writeFile(path.join(root,'.env'),'SECRET=synthetic');await fs.mkdir(path.join(root,'.uih'));await fs.writeFile(path.join(root,'.uih','runtime'),'generated');assert.equal(await sourceRevision(root),base);await fs.unlink(path.join(root,'app.js'));assert.notEqual(await sourceRevision(root),base);});
for(const target of ['image','capture','reference','config','contract','source'])test(`approval invalidated by changed ${target}`,async t=>{const root=await repo(t);const dir=path.join(root,'.uih');await fs.mkdir(dir);const image=path.join(dir,'final.png');await fs.writeFile(image,'image');await fs.writeFile(path.join(dir,'reference.png'),'reference');await fs.writeFile(path.join(dir,'final.capture.json'),'capture');const s={workspace:root,status:'passed',config:{value:1},visualChecks:[],referenceHash:hash('reference'),finalReview:{image}};s.attestation={revision:await sourceRevision(root),referenceHash:s.referenceHash,configHash:hash(JSON.stringify(s.config)),contractHash:hash('[]'),imageHash:hash('image'),captureHash:hash('capture')};assert.equal((await approvalStatus(s)).deliveryReady,true);if(target==='config')s.config.value=2;else if(target==='contract')s.visualChecks.push({key:'changed'});else await fs.writeFile(target==='source'?path.join(root,'app.js'):target==='reference'?path.join(dir,'reference.png'):target==='capture'?path.join(dir,'final.capture.json'):image,'changed');assert.deepEqual(await approvalStatus(s),{status:'stale',deliveryReady:false});});
test('legacy passing results remain unverified',async()=>assert.deepEqual(await approvalStatus({status:'passed'}),{status:'unverified',deliveryReady:false}));
