import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {fixture} from './helpers.mjs';
import {run} from '../src/runner.mjs';
import {git,writeJSON,command,json} from '../src/util.mjs';
async function setup(change){const f=await fixture();f.config.acceptance.visualQuality=0;f.config.acceptance.fidelity=0;f.config.budgets.maxIterations=1;change(f.config);await writeJSON(path.join(f.root,'uih.json'),f.config);await git(f.root,'add','uih.json');await git(f.root,'commit','-m','test configuration');return f;}
test('fresh final judgment can veto an otherwise passing baseline',async()=>{const {root}=await setup(c=>{c.roles.judge.options.finalIssue=true;});const s=await run(root);assert.equal(s.status,'iteration-limit');assert.equal(s.deliveryReady,false);assert.ok(s.finalReview.evaluation.issues.some(i=>i.key==='hero-proportions'));assert.equal(s.attestation,undefined);});
test('final functional failure prevents attestation',async()=>{const {root}=await setup(c=>{c.runtime.options.failCheckAfter=1;});const s=await run(root);assert.notEqual(s.status,'passed');assert.equal(s.attestation,undefined);assert.equal(s.finalReview.checks.passed,false);});
test('missing native selector blocks high-scoring completion',async()=>{const {root}=await setup(c=>{c.visualChecks=[{key:'hero',selector:'id:absent',metric:'aspectRatio',expected:0.75,tolerance:0.05,severity:'major'}];});const s=await run(root);assert.equal(s.status,'iteration-limit');assert.equal(s.issues.find(i=>i.key==='measurement:hero').status,'unverified');});
test('malformed reviewer fails closed and releases project lock',async()=>{const {root}=await setup(c=>{c.roles.judge.options.malformedReview=true;});const s=await run(root);assert.equal(s.status,'failed');assert.match(s.error,/coverage/);await assert.rejects(fs.access(path.join(root,'.uih/run.lock')));assert.equal((await fs.readFile(path.join(s.workspace,'src/Home.tsx'),'utf8')).replace(/\r\n/g,'\n'),'export const value = 0;\n');});
test('CLI run review verify roundtrip preserves historical approval and user edits',async()=>{const {root}=await setup(()=>{});const cli=fileURLToPath(new URL('../bin/uih.mjs',import.meta.url));const invoke=(...args)=>command([process.execPath,cli,...args,'--project',root]);const started=JSON.parse(await invoke('run'));assert.equal(started.status,'passed');const current=JSON.parse(await invoke('review',started.id));assert.equal(current.deliveryReady,true);const historyFile=path.join(root,'.uih/runs',started.id,'state.json');const history=await fs.readFile(historyFile,'utf8');await fs.writeFile(path.join(current.workspace,'new-style.css'),'body { color: red; }');const stale=JSON.parse(await invoke('review',started.id));assert.equal(stale.status,'stale');const verified=JSON.parse(await invoke('verify',started.id,'--workspace',current.workspace));assert.equal(verified.status,'passed');assert.equal(await fs.readFile(historyFile,'utf8'),history);assert.equal(await fs.readFile(path.join(current.workspace,'new-style.css'),'utf8'),'body { color: red; }');await assert.rejects(invoke('unknown-command'),/Unknown command/);});
